publish_to: "none"
name: top_flutter_repo
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^5.0.1
  shared_preferences: ^2.0.18
  intl: ^0.18.0
  connectivity_plus: ^3.0.3
  flutter_screenutil: ^5.6.1
  package_info_plus: ^3.0.3
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/svg/


  # fonts:
  #   - family: Hero New
  #     fonts:
  #       - asset: assets/fonts/Hero_New_Bold.otf
  #       - asset: assets/fonts/Hero_New_Medium.otf
  #       - asset: assets/fonts/Hero_New_Regular.otf
  #       - asset: assets/fonts/Hero_New_SemiBold.otf
  #       - asset: assets/fonts/Hero_New_Light.otf
 



